Add the ability to override fonts (resolves issue #65 )
raviriley/agency-jekyll-theme pull request #78
Opened 2024-02-12 08:40 UTC by avicndugu

This is an enhancement or feature.

## Summary

With this new feature, users can add new fonts, or update current fonts by just editing the style.yml file.

How it works
- Use the "fonts_urls" to add any font to the website.
- Use the "fonts" to match a font mixin with the corresponding font name.

## Context

This is related to GitHub issue #65

2024-02-27 11:15 UTC, raviriley commented
Thanks for the great work @avicndugu!

2024-02-27 11:18 UTC, raviriley requested changes

2024-02-27 11:18 UTC, raviriley commented on _includes/head.html
I believe removing the current font links will break anyone who doesn't have the `style.yml` changes in their version of the project. I would add a check for the existence of custom fonts in `style.yml`, else default to the original links.

2024-02-27 17:46 UTC, avicndugu commented on _includes/head.html
Thanks for the review. I missed providing a fallback.

I have implemented the check for custom fonts to ensure everything works as before without the custom fonts.

2024-02-28 00:02 UTC, raviriley approved these changes

2024-02-28 00:03 UTC, raviriley commented
Thanks for the quick turnaround @avicndugu !

2024-02-28 00:03 UTC, merged